package com.preps.javaconcepts.executorframework.executorpoc.taskmanagement.tasks;

import java.util.concurrent.Callable;

public class ReportTask implements Callable<String> {

    private final String reportName;

    public ReportTask(String reportName) {
        this.reportName = reportName;
    }

    @Override
    public String call() throws Exception {
        try {
            Thread.sleep(1500);
            return "Report '" + reportName + "' generated by thread: " + Thread.currentThread().getName();
        } catch (InterruptedException ex) {
            System.out.println("ReportTask Interrupted: " + reportName);
            Thread.currentThread().interrupt();
            throw ex;
        }

    }
}
